# Generated by Django 5.1.4 on 2024-12-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_review_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/"),
        ),
    ]
